title: Jasen Johnston
logo: "/images/logo.png?raw=true"
<br>
description:
  Experienced software developer with a demonstrated history of working in the industry.
  <br><br>
  Programming:
  <br>
  C#, C++, Java, PHP, JavaScript, jQuery, Ajax, SQL, HTML, and CSS. Developed multiple apps for desktop and mobile. Developed websites for large companies in the West Plains area. Worked with multi-functional teams and familiar with agile and scrum development using design documents and version control.
  <br><br>
  <a href="https://www.linkedin.com/in/jasen-johnston-2a77b615">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
