title: Jasen Johnston # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced software developer with a demonstrated history of working in the industry.
  <br><br>
  Programming: C#, C++, PHP, JavaScript, jQuery, Ajax, SQL, HTML, and CSS. Developed multiple apps for desktop and mobile. Developed websites for large companies in the West Plains area. Worked with multi-functional teams and familiar with agile and scrum development using design documents and version control.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
